// Create Enum for file types

export enum FileType {
    PDF = "pdf",
    DOC = "doc",
    DOCX = "docx",
    XLS = "xls",
    XLSX = "xlsx",
    PPT = "ppt",
    PPTX = "pptx",
    TXT = "txt",
    CSV = "csv",
    JPG = "jpg",
    JPEG = "jpeg",
    PNG = "png",
    GIF = "gif",
    MP3 = "mp3",
    MP4 = "mp4",
    ZIP = "zip",
    RAR = "rar",
    TAR = "tar",
    GZ = "gz",
    BZ2 = "bz2",
    Z = "z",
    OTHER = "other",
}