import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import {ClerkProvider} from "@clerk/nextjs";
import {Toaster} from "@/components/ui/toaster";

import 'simplebar-react/dist/simplebar.min.css'

const popping = Poppins({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body
                className={cn(
                    "min-h-screen bg-background font-sans antialiased",
                    popping.className
                )}
            >
            {children}
            <Toaster/>
            </body>
            </html>
        </ClerkProvider>
    );
}
